site_name: KubeSpace
theme:
  name: null
  custom_dir: 'gitbook/'
nav:
    - 安装配置: index.md
    - 集群管理: cluster/cluster.md
    - 工作空间: 
        - 空间管理: workspace/workspace.md
        - 应用管理: workspace/apps.md
        - 空间资源: workspace/resource.md
        - 成员管理: workspace/member.md
    - 流水线:
        - 流水线空间: pipeline/pipeline_space.md
        - 代码流水线: pipeline/pipeline.md
        - 构建流水线: pipeline/build.md
        - 资源管理: pipeline/resource.md
        - 权限管理: pipeline/member.md
    - 应用商店: appstore/appstore.md
    - 平台配置:
        - 密钥管理: platform/secret.md
        - 镜像仓库: platform/repository.md
        - 用户管理: platform/user.md
        - 平台权限: platform/permission.md
