
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubespace.fullname" . }}-agent
  namespace: {{ .Release.Namespace }}
  labels:
    kubespace-app: kubespace-agent
    {{- include "kubespace.labels" . | nindent 4 }}
  {{- with .Values.agent.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

---

kind: ClusterRoleBinding
{{- if semverCompare "<1.22.0-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: rbac.authorization.k8s.io/v1beta1
{{- else }}
apiVersion: rbac.authorization.k8s.io/v1
{{- end }}
metadata:
  name: {{ include "kubespace.fullname" . }}-agent
  namespace: kubespace
subjects:
  - kind: ServiceAccount
    name: {{ include "kubespace.fullname" . }}-agent
    namespace: kubespace
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubespace.fullname" . }}-agent
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubespace.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      kubespace-app: kubespace-agent
      {{- include "kubespace.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.agent.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        kubespace-app: kubespace-agent
        {{- include "kubespace.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.agent.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kubespace.fullname" . }}-agent
      containers:
        - name: kubespace-agent
          securityContext:
            {{- toYaml .Values.agent.securityContext | nindent 12 }}
          image: "{{ .Values.agent.image.repository }}:{{ .Values.agent.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.agent.image.pullPolicy }}
          command: ["/agent"]
          {{- if .Values.extraArgs }}
          args:
{{ toYaml .Values.extraArgs | indent 12 }}
          {{- end }}
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: SERVER_URL
              value: "{{ include "kubespace.fullname" . }}:{{ .Values.kubespace.service.port }}"
          {{- if .Values.agent.extraEnvs }}
{{ toYaml .Values.agent.extraEnvs | indent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.agent.resources | nindent 12 }}
      {{- with .Values.agent.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.agent.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.agent.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
